### ISSUE TITLE
请问还有在维护吗 有没有文档说明

### ISSUE THREAD

**Issue by kingpingyue** [djbckr/Ora2PgDump#1]
请问还有在维护吗 有没有文档说明

**Comment by djbckr** [comment]
The README file is about as much information as you can get. Try running it through a translator.
自述文件包含您可以获得的尽可能多的信息。 尝试通过翻译器运行它。

**Comment by kingpingyue** [comment]
It lacks Google tools and Oracle to run

**Comment by djbckr** [comment]
As mentioned near the end of the README [here](https://github.com/djbckr/Ora2PgDump#building-your-own-version), you will need to get these libraries and build it yourself.
GSON: https://github.com/google/gson
JODA Time: https://www.joda.org/joda-time/
OJDBC: https://www.oracle.com/database/technologies/appdev/jdbc-downloads.html
It's possible you will need to tweak the source code for it to work with these new versions.
I don't use Oracle any more so I have no way to test this code any more. Sorry.

**Comment by kingpingyue** [comment]
Thank you very much for your reply. I wish you all the best
